/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/k8zdev/k8z/cmd */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "kubernetes.go"
 #include <stdlib.h>
 #include "stdint.h"

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


// PinStatic do nothing, call it at swift just keep the static libarary be linked.
//
extern void PinStatic();

// FreePointer can be used to free a returned pointer.
//
extern void FreePointer(char* ptr);

// LocalServerAddr return listen address of web server.
//
extern char* LocalServerAddr();

// StartLocalServer starts an Go server.
//
extern void StartLocalServer();
extern char* Json2yaml(char* p0);

/* Return type for MultiParams */
struct MultiParams_return {
	char* r0; /* body */
	char* r1; /* err */
};
extern struct MultiParams_return MultiParams(char* name, int nameLen, int64_t timeout, _Bool insecure);

/* Return type for K8zRequest */
struct K8zRequest_return {
	char* r0; /* respC */
	char* r1; /* errC */
};

// K8zRequest
//
extern struct K8zRequest_return K8zRequest(char* serverC, int serverLen, char* caDataC, int caDataLen, _Bool insecureC, char* userCertC, int userCertLen, char* userKeyDataC, int userKeyDataLen, char* userTokenC, int userTokenLen, char* userNameC, int userNameLen, char* userPasswordC, int userPasswordLen, char* proxyC, int proxyLen, int64_t timeoutC, char* methodC, int mehtodLen, char* apiC, int apiLen, char* bodyC, int bodyLen);

#ifdef __cplusplus
}
#endif
