// Mocks generated by Mockito 5.4.6 from annotations
// in k8zdev/test/services/pro_features_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:purchases_flutter/models/customer_info_wrapper.dart' as _i3;
import 'package:purchases_flutter/models/entitlement_info_wrapper.dart' as _i4;
import 'package:purchases_flutter/models/entitlement_infos_wrapper.dart' as _i2;
import 'package:purchases_flutter/models/store.dart' as _i7;
import 'package:purchases_flutter/models/store_transaction.dart' as _i5;
import 'package:purchases_flutter/models/verification_result.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEntitlementInfos_0 extends _i1.SmartFake
    implements _i2.EntitlementInfos {
  _FakeEntitlementInfos_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$CustomerInfoCopyWith_1<$Res> extends _i1.SmartFake
    implements _i3.$CustomerInfoCopyWith<$Res> {
  _Fake$CustomerInfoCopyWith_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$EntitlementInfoCopyWith_2<$Res> extends _i1.SmartFake
    implements _i4.$EntitlementInfoCopyWith<$Res> {
  _Fake$EntitlementInfoCopyWith_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CustomerInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomerInfo extends _i1.Mock implements _i3.CustomerInfo {
  MockCustomerInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.EntitlementInfos get entitlements => (super.noSuchMethod(
        Invocation.getter(#entitlements),
        returnValue: _FakeEntitlementInfos_0(
          this,
          Invocation.getter(#entitlements),
        ),
      ) as _i2.EntitlementInfos);

  @override
  Map<String, String?> get allPurchaseDates => (super.noSuchMethod(
        Invocation.getter(#allPurchaseDates),
        returnValue: <String, String?>{},
      ) as Map<String, String?>);

  @override
  List<String> get activeSubscriptions => (super.noSuchMethod(
        Invocation.getter(#activeSubscriptions),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String> get allPurchasedProductIdentifiers => (super.noSuchMethod(
        Invocation.getter(#allPurchasedProductIdentifiers),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<_i5.StoreTransaction> get nonSubscriptionTransactions =>
      (super.noSuchMethod(
        Invocation.getter(#nonSubscriptionTransactions),
        returnValue: <_i5.StoreTransaction>[],
      ) as List<_i5.StoreTransaction>);

  @override
  String get firstSeen => (super.noSuchMethod(
        Invocation.getter(#firstSeen),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#firstSeen),
        ),
      ) as String);

  @override
  String get originalAppUserId => (super.noSuchMethod(
        Invocation.getter(#originalAppUserId),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#originalAppUserId),
        ),
      ) as String);

  @override
  Map<String, String?> get allExpirationDates => (super.noSuchMethod(
        Invocation.getter(#allExpirationDates),
        returnValue: <String, String?>{},
      ) as Map<String, String?>);

  @override
  String get requestDate => (super.noSuchMethod(
        Invocation.getter(#requestDate),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#requestDate),
        ),
      ) as String);

  @override
  _i3.$CustomerInfoCopyWith<_i3.CustomerInfo> get copyWith =>
      (super.noSuchMethod(
        Invocation.getter(#copyWith),
        returnValue: _Fake$CustomerInfoCopyWith_1<_i3.CustomerInfo>(
          this,
          Invocation.getter(#copyWith),
        ),
      ) as _i3.$CustomerInfoCopyWith<_i3.CustomerInfo>);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [EntitlementInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockEntitlementInfo extends _i1.Mock implements _i4.EntitlementInfo {
  MockEntitlementInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get identifier => (super.noSuchMethod(
        Invocation.getter(#identifier),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#identifier),
        ),
      ) as String);

  @override
  bool get isActive => (super.noSuchMethod(
        Invocation.getter(#isActive),
        returnValue: false,
      ) as bool);

  @override
  bool get willRenew => (super.noSuchMethod(
        Invocation.getter(#willRenew),
        returnValue: false,
      ) as bool);

  @override
  String get latestPurchaseDate => (super.noSuchMethod(
        Invocation.getter(#latestPurchaseDate),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#latestPurchaseDate),
        ),
      ) as String);

  @override
  String get originalPurchaseDate => (super.noSuchMethod(
        Invocation.getter(#originalPurchaseDate),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#originalPurchaseDate),
        ),
      ) as String);

  @override
  String get productIdentifier => (super.noSuchMethod(
        Invocation.getter(#productIdentifier),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#productIdentifier),
        ),
      ) as String);

  @override
  bool get isSandbox => (super.noSuchMethod(
        Invocation.getter(#isSandbox),
        returnValue: false,
      ) as bool);

  @override
  _i4.OwnershipType get ownershipType => (super.noSuchMethod(
        Invocation.getter(#ownershipType),
        returnValue: _i4.OwnershipType.purchased,
      ) as _i4.OwnershipType);

  @override
  _i7.Store get store => (super.noSuchMethod(
        Invocation.getter(#store),
        returnValue: _i7.Store.appStore,
      ) as _i7.Store);

  @override
  _i4.PeriodType get periodType => (super.noSuchMethod(
        Invocation.getter(#periodType),
        returnValue: _i4.PeriodType.intro,
      ) as _i4.PeriodType);

  @override
  _i8.VerificationResult get verification => (super.noSuchMethod(
        Invocation.getter(#verification),
        returnValue: _i8.VerificationResult.notRequested,
      ) as _i8.VerificationResult);

  @override
  _i4.$EntitlementInfoCopyWith<_i4.EntitlementInfo> get copyWith =>
      (super.noSuchMethod(
        Invocation.getter(#copyWith),
        returnValue: _Fake$EntitlementInfoCopyWith_2<_i4.EntitlementInfo>(
          this,
          Invocation.getter(#copyWith),
        ),
      ) as _i4.$EntitlementInfoCopyWith<_i4.EntitlementInfo>);

  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
